server:
  port: 8078
spring:
  application:
    name: cards
  datasource:
    url: jdbc:postgresql://localhost:5432/cardsdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: rocks
  jpa:
    show-sql: true
    sql:
      init:
        mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"