apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  db-init.sh: |
    #!/bin/bash
    export PGPASSWORD="${POSTGRESQL_PASSWORD}"

    create_db_if_not_exists() {
      local db="$1"
      echo "Checking if database $db exists..."
      if ! psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$db'" | grep -q 1; then
        echo "Creating database $db"
        psql -U postgres -c "CREATE DATABASE $db"
      else
        echo "Database $db already exists, skipping."
      fi
    }

    create_db_if_not_exists accountsdb
    create_db_if_not_exists cardsdb
    create_db_if_not_exists loansdb

    echo "Running schema scripts..."
    psql -U postgres -d accountsdb -f /docker-entrypoint-initdb.d/accounts.sql
    psql -U postgres -d cardsdb -f /docker-entrypoint-initdb.d/cards.sql
    psql -U postgres -d loansdb -f /docker-entrypoint-initdb.d/loans.sql

  accounts.sql: |
    CREATE TABLE IF NOT EXISTS customer (
       customer_id serial  PRIMARY KEY,
       name varchar(100) NOT NULL,
       email varchar(100) NOT NULL,
       mobile_number varchar(20) NOT NULL,
       created_at date NOT NULL,
       created_by varchar(20) NOT NULL,
       updated_at date DEFAULT NULL,
       updated_by varchar(20) DEFAULT NULL
    );
  
    CREATE TABLE IF NOT EXISTS accounts (
       customer_id int NOT NULL,
       account_number serial  PRIMARY KEY,
       account_type varchar(100) NOT NULL,
       branch_address varchar(200) NOT NULL,
       communication_sw boolean,
       created_at date NOT NULL,
       created_by varchar(20) NOT NULL,
       updated_at date DEFAULT NULL,
       updated_by varchar(20) DEFAULT NULL
    );

  cards.sql: |
    CREATE TABLE IF NOT EXISTS cards (
        card_id serial PRIMARY KEY,
        mobile_number varchar(15) NOT NULL,
        card_number varchar(100) NOT NULL,
        card_type varchar(100) NOT NULL,
        total_limit int NOT NULL,
        amount_used int NOT NULL,
        available_amount int NOT NULL,
        created_at date NOT NULL,
        created_by varchar(20) NOT NULL,
        updated_at date DEFAULT NULL,
        updated_by varchar(20) DEFAULT NULL
    );

  loans.sql: |
    CREATE TABLE IF NOT EXISTS loans (
       loan_id serial  PRIMARY KEY,
       mobile_number varchar(15) NOT NULL,
       loan_number varchar(100) NOT NULL,
       loan_type varchar(100) NOT NULL,
       total_loan int NOT NULL,
       amount_paid int NOT NULL,
       outstanding_amount int NOT NULL,
       created_at date NOT NULL,
       created_by varchar(20) NOT NULL,
       updated_at date DEFAULT NULL,
       updated_by varchar(20) DEFAULT NULL
    );
