spring:
  application:
    name: configserver
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///C://Users//Lenovo//config"
         git:
           uri: https://github.com/fbz-tec/eazybytes-config.git
           default-label: main
           timeout: 5
           clone-on-start: true
           force-pull: true

server:
  port: 8071
encrypt:
  key: "C36FD3AFDC574C179EFAE278CF145"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
