# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: message-deployment
serviceName: message
appLabel: message
appName: message

replicaCount: 1

image:
  repository: fbz-tec/message
  tag: s14

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

dbUrl: jdbc:postgresql://postgres:5432/loansdb

appname_enabled: true
profile_enabled: true
config_enabled: false
discovery_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
rabbitmq_enabled: true
postgresdb_enabled: false